name: Close Issue on PR Approval

on:
  pull_request:
    types: [closed]

jobs:
  close_issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Set up GitHub CLI
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Close referenced issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_BODY=$(gh pr view $PR_NUMBER --json body -q .body)
          
          # Assume a sintaxe "Fixes #<numero_issue>"
          ISSUE_NUMBERS=$(echo "$PR_BODY" | grep -oE '#[0-9]+' | tr -d '#')
          
          for ISSUE_NUMBER in $ISSUE_NUMBERS; do
            gh issue close $ISSUE_NUMBER --comment "Closed by PR #${PR_NUMBER} which has been merged."
          done
